CREATE TABLE user_tbl (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role_id BIGINT,
  FOREIGN KEY (role_id) REFERENCES role_tbl(id)
);